# Generated by Django 5.1.2 on 2024-10-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Expenses',
        ),
        migrations.RenameModel(
            old_name='Musician',
            new_name='Investments',
        ),
    ]
