# Generated by Django 5.1.2 on 2024-10-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_album_expenses_rename_musician_investments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investments',
            old_name='first_name',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='investments',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='investments',
            old_name='instrument',
            new_name='profit',
        ),
    ]
