# Generated by Django 5.1.2 on 2024-10-31 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_first_name_investments_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
        migrations.RenameModel(
            old_name='Investments',
            new_name='Investment',
        ),
    ]
