# Generated by Django 5.1.2 on 2024-10-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_expenses_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='profit',
        ),
        migrations.AddField(
            model_name='investment',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
