# Generated by Django 5.1.2 on 2024-10-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_investment_profit_investment_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='num_stars',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='release_date',
        ),
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
