# Generated by Django 5.1.2 on 2024-10-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_expense_artist_remove_expense_num_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='percentage',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
