# Generated by Django 5.1.2 on 2024-10-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_expense_amount_alter_investment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='years',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
