# Generated by Django 5.1.2 on 2024-10-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_investment_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='years',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='years',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
