# Generated by Django 5.1.2 on 2024-10-31 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_expense_years_alter_investment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='years',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='years',
        ),
    ]
