# Generated by Django 5.1.2 on 2024-10-31 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_expense2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense2',
        ),
    ]
