# Generated by Django 5.1.2 on 2024-10-31 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_delete_expense2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalConfig',
        ),
    ]
