# Generated by Django 5.1.2 on 2024-11-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_investment_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='years',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
