# Generated by Django 5.1.2 on 2024-11-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_expense_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='monthly_contribution',
            field=models.IntegerField(default=0),
        ),
    ]
